### ISSUE TITLE
Hello I found that your public dataset cannot be downloaded

### ISSUE THREAD

**Issue by Yzwfff** [CAU-HE/CMCDNet#1]
Hello I found that your public dataset is not downloadable on Baidu.com, can you please share one?

**Comment by CAU-HE** [comment]
Hi, the download link is alive. The data is shared using Baidu Yun, make sure you have the Baidu netdisk installed before downloading the data. If you have further problems accessing the data, just let me know, I may upload to some other cloud service.

**Comment by Yzwfff** [comment]
Thank you for your Q&A, I have successfully downloaded it. Thank you for sharing the data.

**Comment by CAU-HE** [comment]
You're welcome.
